from __future__ import annotations

import os
import uuid

import jaydebeapi


H2_JDBC_URL = os.getenv(
    "H2_JDBC_URL",
    "jdbc:h2:tcp://localhost:9092/mem:arbitlocal;MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1",
)


SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) NOT NULL UNIQUE,
        created_at TIMESTAMP,
        updated_at TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS events (
        id BINARY(16) NOT NULL PRIMARY KEY,
        category_id BIGINT NOT NULL,
        title VARCHAR(200) NOT NULL,
        description CLOB,
        poster_image_url VARCHAR(1000),
        venue VARCHAR(100) NOT NULL,
        venue_address VARCHAR(255),
        district VARCHAR(50) NOT NULL,
        latitude DOUBLE,
        longitude DOUBLE,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        free BOOLEAN NOT NULL,
        status VARCHAR(20) NOT NULL,
        average_rating DECIMAL(3,2) NOT NULL DEFAULT 0.00,
        price VARCHAR(255),
        booking_url VARCHAR(1000),
        created_at TIMESTAMP,
        updated_at TIMESTAMP,
        CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS keywords (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        type VARCHAR(30) NOT NULL,
        value VARCHAR(80) NOT NULL,
        created_at TIMESTAMP,
        updated_at TIMESTAMP,
        CONSTRAINT uk_keyword_type_value UNIQUE (type, value)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS event_keyword_weights (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BINARY(16) NOT NULL,
        keyword_id BIGINT NOT NULL,
        weight DECIMAL(5,4) NOT NULL,
        source VARCHAR(30) NOT NULL,
        created_at TIMESTAMP,
        updated_at TIMESTAMP,
        CONSTRAINT uk_event_keyword_weight UNIQUE (event_id, keyword_id),
        CONSTRAINT fk_event_keyword_weights_event FOREIGN KEY (event_id) REFERENCES events(id),
        CONSTRAINT fk_event_keyword_weights_keyword FOREIGN KEY (keyword_id) REFERENCES keywords(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS age_restriction_keywords (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        value VARCHAR(50) NOT NULL UNIQUE,
        created_at TIMESTAMP,
        updated_at TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS event_age_restrictions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BINARY(16) NOT NULL UNIQUE,
        age_restriction_keyword_id BIGINT NOT NULL,
        created_at TIMESTAMP,
        updated_at TIMESTAMP,
        CONSTRAINT fk_event_age_restrictions_event FOREIGN KEY (event_id) REFERENCES events(id),
        CONSTRAINT fk_event_age_restrictions_keyword FOREIGN KEY (age_restriction_keyword_id) REFERENCES age_restriction_keywords(id)
    )
    """,
]


EVENTS = [
    ("550e8400-e29b-41d4-a716-446655440000", "Seoul Media Art Exhibition", "exhibition", "강남구", True, "2026-06-10", "2026-06-30", "아동/가족 제외", ["힐링/감성", "학술/사색적"]),
    ("550e8400-e29b-41d4-a716-446655440001", "Modern Art Showcase", "exhibition", "마포구", False, "2026-07-01", "2026-07-20", "아동/가족 제외", ["힐링/감성"]),
    ("550e8400-e29b-41d4-a716-446655440002", "Indie Band Live", "concert", "홍대", False, "2026-06-15", "2026-06-15", "아동/가족 제외", ["감동/웅장"]),
    ("550e8400-e29b-41d4-a716-446655440003", "Classical Night", "concert", "서초구", False, "2026-08-01", "2026-08-01", "아동/가족 제외", ["감동/웅장", "학술/사색적"]),
    ("550e8400-e29b-41d4-a716-446655440004", "Theater Festival", "performance", "종로구", True, "2026-07-10", "2026-07-13", "아동/가족 제외", ["가족친화"]),
    ("550e8400-e29b-41d4-a716-446655440005", "Dance Performance", "performance", "중구", False, "2026-09-01", "2026-09-03", "아동/가족 제외", ["감동/웅장"]),
    ("550e8400-e29b-41d4-a716-446655440006", "Design Fair", "exhibition", "성동구", True, "2026-06-20", "2026-07-20", "아동/가족 제외", ["학술/사색적"]),
    ("550e8400-e29b-41d4-a716-446655440007", "Jazz Evening", "concert", "용산구", False, "2026-10-12", "2026-10-12", "아동/가족 제외", ["힐링/감성"]),
    ("550e8400-e29b-41d4-a716-446655440008", "Family Musical", "performance", "송파구", False, "2026-11-01", "2026-11-10", "전체", ["가족친화"]),
    ("550e8400-e29b-41d4-a716-446655440009", "Photo Archive", "exhibition", "은평구", True, "2026-12-01", "2026-12-31", "전체", ["학술/사색적"]),
    ("550e8400-e29b-41d4-a716-446655440010", "Outdoor Cinema", "movie", "여의도", True, "2026-06-25", "2026-06-25", "전체", ["가족친화", "힐링/감성"]),
    ("550e8400-e29b-41d4-a716-446655440011", "Traditional Music Day", "concert", "종로구", True, "2026-07-05", "2026-07-05", "아동/가족 제외", ["감동/웅장"]),
]


def scalar(cursor, sql: str, params=()):
    cursor.execute(sql, params)
    return cursor.fetchone()[0]


def main() -> None:
    h2_jar = os.environ["H2_JAR_PATH"]
    conn = jaydebeapi.connect("org.h2.Driver", H2_JDBC_URL, ["sa", ""], h2_jar)
    try:
        cursor = conn.cursor()
        for statement in SCHEMA:
            cursor.execute(statement)

        for category in sorted({event[2] for event in EVENTS}):
            cursor.execute(
                "MERGE INTO categories (name, created_at, updated_at) KEY(name) VALUES (?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                (category,),
            )

        for age in sorted({event[7] for event in EVENTS}):
            cursor.execute(
                "MERGE INTO age_restriction_keywords (value, created_at, updated_at) KEY(value) VALUES (?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                (age,),
            )

        for keyword_type, value in sorted({("MOOD", mood) for event in EVENTS for mood in event[8]} | {("AGE", event[7]) for event in EVENTS}):
            cursor.execute(
                "MERGE INTO keywords (type, value, created_at, updated_at) KEY(type, value) VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                (keyword_type, value),
            )

        for event_id, title, category, district, is_free, start_date, end_date, age, moods in EVENTS:
            category_id = scalar(cursor, "SELECT id FROM categories WHERE name = ?", (category,))
            hex_id = uuid.UUID(event_id).hex
            cursor.execute(
                f"""
                MERGE INTO events (
                    id, category_id, title, description, poster_image_url, venue,
                    district, start_date, end_date, free, status, average_rating,
                    price, booking_url, created_at, updated_at
                ) KEY(id) VALUES (
                    X'{hex_id}', ?, ?, ?, ?, ?, ?, ?, ?, ?, 'UPCOMING', 0.00,
                    ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                )
                """,
                (
                    category_id,
                    title,
                    f"{title} description",
                    "https://storage.googleapis.com/deepflow-image-storage/background-image/image_1.png",
                    "Local H2 Venue",
                    district,
                    start_date,
                    end_date,
                    is_free,
                    "무료" if is_free else "유료",
                    "https://example.com",
                ),
            )

            age_keyword_id = scalar(cursor, "SELECT id FROM age_restriction_keywords WHERE value = ?", (age,))
            cursor.execute(
                f"MERGE INTO event_age_restrictions (event_id, age_restriction_keyword_id, created_at, updated_at) KEY(event_id) VALUES (X'{hex_id}', ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                (age_keyword_id,),
            )

            age_weight_keyword_id = scalar(cursor, "SELECT id FROM keywords WHERE type = 'AGE' AND value = ?", (age,))
            cursor.execute(
                f"MERGE INTO event_keyword_weights (event_id, keyword_id, weight, source, created_at, updated_at) KEY(event_id, keyword_id) VALUES (X'{hex_id}', ?, 1.0000, 'h2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                (age_weight_keyword_id,),
            )
            mood_weight = round(1 / len(moods), 4)
            for mood in moods:
                mood_keyword_id = scalar(cursor, "SELECT id FROM keywords WHERE type = 'MOOD' AND value = ?", (mood,))
                cursor.execute(
                    f"MERGE INTO event_keyword_weights (event_id, keyword_id, weight, source, created_at, updated_at) KEY(event_id, keyword_id) VALUES (X'{hex_id}', ?, ?, 'h2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                    (mood_keyword_id, mood_weight),
                )

        conn.commit()
        cursor.execute("SELECT COUNT(*) FROM events")
        print(f"seeded events={cursor.fetchone()[0]}")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
